export const productList = [
  {
    id: 1,
    title: "Choco Banana",
    description: "Banana blended with rich chocolate.",
    image: "/image/card1.jfif",
    price: "60.000 IDR",
  },

  {
    id: 2,
    title: "Honey Milk Glow",
    description: "Milk and natural honey blend.",
    image: "/image/card2.jfif",
    price: "65.000 IDR",
  },
  {
    id: 3,
    title: "Strawberry Dream",
    description: "Fresh strawberry smoothie.",
    image: "/image/card3.jfif",
    price: "70.000 IDR",
  },
  {
    id: 4,
    title: "Green Goddess",
    description: "Avocado & spinach healthy bowl.",
    image: "/image/card4.jfif",
    price: "75.000 IDR",
  },
  {
    id: 5,
    title: "Tropical Sunrise",
    description: "Pineapple and mixed berries blend.",
    image: "/image/card5.jfif",
    price: "55.000 IDR",
  },
  {
    id: 6,
    title: "Berry Blast",
    description: "Mixed berries with a creamy smoothie base.",
    image: "/image/card6.jfif",
    price: "58.000 IDR",
  },
  {
    id: 7,
    title: "Peachy Keen Bowl",
    description: "Peach smoothie topped with nuts and seeds.",
    image: "/image/card7.jfif",
    price: "48.000 IDR",
  },
  {
    id: 8,
    title: "Kiwi Cooler",
    description: "Kiwi and apple blend.",
    image: "/image/card8.jfif",
    price: "45.000 IDR",
  },
  {
    id: 9,
    title: "Unicorn Magic",
    description: "Dragon fruit & spirulina glitter bowl.",
    image: "/image/card9.jfif",
    price: "85.000 IDR",
  },
  {
    id: 10,
    title: "Mango Breeze",
    description: "Mango and pineapple fusion.",
    image: "/image/card10.jfif",
    price: "64.000 IDR",
  },
  {
    id: 11,
    title: "Forest Berry Bowl",
    description: "Lush green smoothie topped with berries.",
    image: "/image/card11.jfif",
    price: "54.000 IDR",
  },
  {
    id: 12,
    title: "Cacao Bliss",
    description: "Cocoa, banana, and almond milk.",
    image: "/image/card12.jfif",
    price: "70.000 IDR",
  },
];
